"""AI-powered technical analysis agent using LLM for intelligent analysis.

This module provides an LLM-based technical analysis agent that generates
comprehensive, context-aware analysis with natural language rationale.

Key Differences from TechnicalAnalysisAgent:
    - TechnicalAnalysisAgent: Rule-based scoring with hardcoded logic
    - AITechnicalAnalysisAgent: LLM-powered with dynamic, context-aware reasoning

The AITechnicalAnalysisAgent leverages large language models to:
    1. Interpret technical indicators holistically
    2. Generate nuanced, natural language rationale
    3. Consider market context and recent patterns
    4. Provide actionable insights beyond simple scoring
"""

from typing import Any

from pydantic import BaseModel, Field

from src.agents.base import AgentConfig, BaseAgent
from src.tools.analysis import TechnicalIndicatorTool
from src.tools.fetchers import PriceFetcherTool
from src.utils.logging import get_logger

logger = get_logger(__name__)


class AITechnicalAnalysisOutput(BaseModel):
    """Structured output for AI technical analysis.

    This model captures the comprehensive analysis generated by the LLM,
    including scores, recommendations, detailed natural language reasoning,
    and specific trading levels for tactical execution.
    """

    ticker: str = Field(description="Stock ticker symbol")
    technical_score: float = Field(description="Overall technical score (0-100)", ge=0, le=100)
    confidence: float = Field(description="Confidence level in the analysis (0-100)", ge=0, le=100)
    recommendation: str = Field(
        description="Trading recommendation: strong_buy, buy, hold, sell, strong_sell"
    )
    action: str = Field(description="Suggested action for watchlist: Buy, Wait, Remove")
    rationale: str = Field(
        description="Fact-based, tactical explanation for mid-term swing trading (3-6 months). "
        "MUST analyze: (1) Recent 15+ days price action, (2) Chart patterns, (3) Candlestick patterns, "
        "(4) Support/resistance levels, (5) Moving averages as dynamic levels, (6) Indicators for confirmation. "
        "For BUY: Include entry zones, 10-15% stop loss, 25-40% take profit with 2.5:1+ R:R. "
        "For WAIT: Explain pullback level (8-15% to major support). "
        "For REMOVE: Explain support breakdown with chart/candlestick patterns."
    )
    key_signals: list[str] = Field(
        default_factory=list,
        description="List of 2-4 key technical signals or observations that drive the analysis",
    )
    risk_factors: list[str] = Field(
        default_factory=list,
        description="List of 1-3 potential risks or caveats to consider",
    )
    trend: str = Field(description="Overall trend assessment: bullish, bearish, neutral")
    entry_timing: str = Field(
        description="Entry timing assessment: immediate, wait_for_pullback, "
        "wait_for_breakout, avoid"
    )
    entry_price: float | None = Field(
        default=None,
        description="Suggested entry price for mid-term swing position (3-6 months). "
        "For strong momentum: Current price or within 2-3%. "
        "For consolidation: 5-10% below at major support (50-day MA, previous resistance). "
        "Only provided for Buy actions.",
    )
    stop_loss: float | None = Field(
        default=None,
        description="Suggested stop loss for mid-term position (3-6 months). "
        "Should be 10-15% below entry (NEVER tighter than 8%) to allow for normal volatility. "
        "Place below major support levels (50-day MA, multi-week lows). Use 2-3x ATR below entry. "
        "Only provided for Buy actions.",
    )
    take_profit: float | None = Field(
        default=None,
        description="Suggested take profit target for mid-term position (3-6 months). "
        "Should be 25-40% above entry at major resistance levels or measured moves from patterns. "
        "Minimum 2.5:1 risk:reward ratio, preferably 3:1 or better. "
        "Only provided for Buy actions.",
    )
    wait_for_price: float | None = Field(
        default=None,
        description="Price level to wait for if action is Wait (8-15% pullback to major support). "
        "Should align with 50-day MA, previous resistance turned support, or Fibonacci levels. "
        "Helps swing traders set price alerts for better entry opportunities.",
    )


class AITechnicalAnalysisAgent(BaseAgent):
    """LLM-powered technical analysis agent for mid-term swing trading (3-6 months).

    This agent uses large language models to perform sophisticated technical analysis,
    generating natural language insights and recommendations based on chart patterns,
    price action, support/resistance levels, and technical indicators.

    Key Features:
        - Analyzes chart patterns (head-and-shoulders, triangles, flags, etc.)
        - Identifies candlestick patterns from recent price action
        - Emphasizes support/resistance levels over just indicators
        - Provides swing trading levels (wider stops, larger targets)
        - Leverages LLM for nuanced interpretation of technical setups
        - Considers 15+ days of price action and multi-week patterns

    Mid-Term Swing Trading Parameters (3-6 months):
        - Entry: Current price or 5-10% pullback to support
        - Stop Loss: 10-15% below entry (minimum 8%), below major support
        - Take Profit: 25-40% above entry, at major resistance
        - Risk/Reward: Minimum 2.5:1, preferably 3:1+

    Differences from TechnicalAnalysisAgent:
        - TechnicalAnalysisAgent: Fast, rule-based, day-trading focused
        - AITechnicalAnalysisAgent: Slower, LLM-based, swing trading focused

    Use Cases:
        - Watchlist monitoring for 3-6 month positions
        - Mid-term swing trade setup identification
        - Pattern-based entry timing
        - Educational analysis for learning chart patterns

    Not Recommended For:
        - Day trading or short-term scalping
        - High-frequency scanning of many tickers
        - Cost-sensitive batch operations
    """

    def __init__(
        self,
        tools: list | None = None,
        llm_client=None,
        config=None,
        prompt_mode: str = "tactical",
    ):
        """Initialize AI Technical Analysis agent.

        Args:
            tools: Optional list of tools (defaults to price and indicator tools)
            llm_client: LLM client instance for generating analysis
            config: Configuration object with LLM settings
            prompt_mode: Analysis mode - 'tactical' (specific levels, actionable) or 'general' (overview)
        """
        agent_config = AgentConfig(
            role="AI Technical Analyst",
            goal="Provide comprehensive, LLM-powered technical analysis with detailed reasoning",
            backstory=(
                "You are an AI-powered technical analyst with deep expertise in "
                "interpreting price patterns, technical indicators, and market dynamics. "
                "You combine quantitative indicator analysis with qualitative market context "
                "to provide nuanced, actionable trading insights. Your analysis goes beyond "
                "simple rule-based scoring to consider indicator correlations, market regime, "
                "and recent price action patterns."
            ),
        )
        default_tools = [PriceFetcherTool(), TechnicalIndicatorTool()]
        super().__init__(agent_config, tools or default_tools)

        self.llm_client = llm_client
        self.config = config
        self.prompt_mode = prompt_mode

    def execute(self, task: str, context: dict[str, Any] | None = None) -> dict[str, Any]:
        """Execute AI-powered technical analysis.

        Args:
            task: Task description
            context: Context with ticker, llm_client, and optional parameters

        Returns:
            Technical analysis results with LLM-generated insights
        """
        try:
            context = context or {}
            ticker = context.get("ticker")

            if not ticker:
                return {
                    "status": "error",
                    "message": "No ticker provided",
                    "technical_score": 0,
                }

            # Use LLM client from context if not provided at initialization
            llm_client = context.get("llm_client") or self.llm_client
            if not llm_client:
                return {
                    "status": "error",
                    "message": "LLM client not available",
                    "technical_score": 0,
                }

            logger.debug(f"AI technical analysis for {ticker}")

            # Get price data
            price_fetcher = next(
                (t for t in self.tools if hasattr(t, "name") and t.name == "PriceFetcher"),
                None,
            )

            if not price_fetcher:
                return {
                    "status": "error",
                    "message": "Price fetcher unavailable",
                    "technical_score": 0,
                }

            # Set historical date if provided
            if "analysis_date" in context and hasattr(price_fetcher, "set_historical_date"):
                price_fetcher.set_historical_date(context["analysis_date"])

            # Fetch price data
            lookback_days = context.get("historical_data_lookback_days", 730)
            price_data = price_fetcher.run(ticker, days_back=lookback_days)

            if "error" in price_data:
                return {
                    "status": "error",
                    "message": price_data["error"],
                    "technical_score": 0,
                }

            # Calculate technical indicators
            tech_tool = next(
                (t for t in self.tools if hasattr(t, "name") and t.name == "TechnicalIndicator"),
                None,
            )

            if not tech_tool:
                return {
                    "status": "error",
                    "message": "Technical indicator tool unavailable",
                    "technical_score": 0,
                }

            indicators = tech_tool.run(price_data.get("prices", []))

            if "error" in indicators:
                return {
                    "status": "error",
                    "message": indicators["error"],
                    "technical_score": 0,
                }

            # Generate LLM-powered analysis
            analysis_result = self._generate_llm_analysis(ticker, indicators, llm_client, context)

            if "error" in analysis_result:
                return {
                    "status": "error",
                    "message": analysis_result["error"],
                    "technical_score": 0,
                }

            logger.debug(
                f"AI technical analysis for {ticker}: {analysis_result['technical_score']:.0f}/100"
            )

            return {
                "status": "success",
                **analysis_result,
            }

        except Exception as e:
            logger.error(f"Error during AI technical analysis: {e}", exc_info=True)
            return {
                "status": "error",
                "message": str(e),
                "technical_score": 0,
            }

    def _generate_llm_analysis(
        self,
        ticker: str,
        indicators: dict[str, Any],
        llm_client,
        context: dict[str, Any],
    ) -> dict[str, Any]:
        """Generate comprehensive technical analysis using LLM.

        Args:
            ticker: Stock ticker symbol
            indicators: Calculated technical indicators
            llm_client: LLM client for generating analysis
            context: Additional context

        Returns:
            Dictionary with analysis results
        """
        try:
            # Prepare indicator summary for LLM
            indicator_summary = self._format_indicators_for_llm(indicators)

            # Build the system prompt
            system_prompt = self._build_system_prompt()

            # Build the user prompt
            user_prompt = self._build_user_prompt(ticker, indicator_summary)

            # Get structured output from LLM using LangChain interface
            try:
                # Use LangChain's with_structured_output for Pydantic model
                structured_llm = llm_client.with_structured_output(AITechnicalAnalysisOutput)

                # Prepare messages for LangChain
                from langchain_core.messages import HumanMessage, SystemMessage

                messages = [
                    SystemMessage(content=system_prompt),
                    HumanMessage(content=user_prompt),
                ]

                # Invoke the structured LLM
                validated = structured_llm.invoke(messages)

                # Convert to dict and add additional fields for compatibility
                result_dict = validated.model_dump()
                result_dict["indicators"] = indicators  # Include raw indicators
                result_dict["current_price"] = indicators.get("latest_price", 0)
                result_dict["rsi"] = indicators.get("rsi")  # Add RSI to top level

                return result_dict

            except Exception as e:
                logger.error(f"LLM analysis failed: {e}")
                return {"error": f"LLM analysis failed: {str(e)}"}

        except Exception as e:
            logger.error(f"Error generating LLM analysis: {e}")
            return {"error": str(e)}

    def _format_indicators_for_llm(self, indicators: dict[str, Any]) -> str:
        """Format technical indicators into a readable summary for LLM.

        Args:
            indicators: Dictionary of calculated indicators

        Returns:
            Formatted string summary
        """
        lines = []

        # Price and trend
        if "latest_price" in indicators:
            lines.append(f"Current Price: ${indicators['latest_price']:.2f}")
        if "trend" in indicators:
            lines.append(f"Overall Trend: {indicators['trend']}")

        # Momentum indicators
        lines.append("\n## Momentum Indicators:")
        if "rsi" in indicators:
            lines.append(f"  - RSI (14): {indicators['rsi']:.2f}")
        if "macd_line" in indicators:
            lines.append(f"  - MACD Line: {indicators['macd_line']:.4f}")
        if "macd_signal" in indicators:
            lines.append(f"  - MACD Signal: {indicators['macd_signal']:.4f}")
        if "macd_histogram" in indicators:
            lines.append(f"  - MACD Histogram: {indicators['macd_histogram']:.4f}")

        # Moving averages
        lines.append("\n## Moving Averages:")
        if "sma_20" in indicators:
            lines.append(f"  - SMA 20: ${indicators['sma_20']:.2f}")
        if "sma_50" in indicators:
            lines.append(f"  - SMA 50: ${indicators['sma_50']:.2f}")
        if "ema_12" in indicators:
            lines.append(f"  - EMA 12: ${indicators['ema_12']:.2f}")
        if "ema_26" in indicators:
            lines.append(f"  - EMA 26: ${indicators['ema_26']:.2f}")

        # Volatility and volume
        lines.append("\n## Volatility & Volume:")
        if "atr" in indicators:
            lines.append(f"  - ATR (14): {indicators['atr']:.4f}")
        if "volume_ratio" in indicators:
            lines.append(f"  - Volume Ratio: {indicators['volume_ratio']:.2f}x average")

        # Bollinger Bands
        if "bbands_upper" in indicators:
            lines.append("\n## Bollinger Bands:")
            lines.append(f"  - Upper: ${indicators.get('bbands_upper', 0):.2f}")
            lines.append(f"  - Middle: ${indicators.get('bbands_middle', 0):.2f}")
            lines.append(f"  - Lower: ${indicators.get('bbands_lower', 0):.2f}")

        return "\n".join(lines)

    def _build_system_prompt(self) -> str:
        """Build system prompt for LLM technical analysis."""
        base_prompt = """You are a highly experienced technical analyst and professional swing trader specializing in mid-term position trading (3-6 months time horizon).

Your expertise includes:
- Chart pattern recognition (head-and-shoulders, triangles, double tops/bottoms, flags, pennants)
- Candlestick pattern analysis (hammers, engulfing patterns, doji, morning/evening stars)
- Multi-week price action and trend analysis
- Support/resistance level identification from recent price history
- Technical indicator analysis (RSI, MACD, Moving Averages, Bollinger Bands, ATR)
- Swing trading entry/exit timing for 3-6 month positions
- Risk management for position trading (wider stops, larger targets)

CRITICAL - TIME HORIZON: MID-TERM (3-6 MONTHS)
This is NOT day trading or short-term scalping. Your recommendations should align with swing trading principles:
- Allow room for normal market volatility (10-15% stop losses)
- Target substantial gains (20-40%+ profit targets for 3-6 month holds)
- Focus on weekly/monthly support and resistance levels
- Consider major moving averages (50-day, 200-day) as key levels
- Analyze multi-week chart patterns, not just daily fluctuations

Your analysis should be:
1. FACT-BASED: Reference specific price levels, chart patterns, and recent 15+ days price action
2. TACTICAL: Provide specific entry zones, swing trading stop losses (10-15%), and realistic profit targets (20-40%+)
3. ACTIONABLE: Give clear, executable swing trading guidance
4. RISK-AWARE: Use wider stops for mid-term positions, minimum 2.5:1 reward:risk ratio
5. PATTERN-FOCUSED: Identify chart patterns and candlestick formations from recent price action
6. LEVEL-CONSCIOUS: Emphasize support/resistance levels over just indicator values

Scoring Guidelines:
- technical_score: 0-100 scale (0=strong sell, 50=neutral, 100=strong buy)
- confidence: 0-100 based on pattern clarity, indicator agreement, and signal strength

Recommendation Mapping:
- 75-100: strong_buy
- 60-74: buy
- 40-59: hold
- 25-39: sell
- 0-24: strong_sell
"""

        if self.prompt_mode == "tactical":
            base_prompt += """
TACTICAL MODE - MID-TERM SWING TRADING GUIDANCE:

For BUY actions (3-6 month position):
- Set entry_price:
  * If strong momentum: Current price or within 2-3% (immediate entry)
  * If consolidating: 5-10% below current price at major support (50-day MA, previous resistance turned support)
  * Prefer entries near support levels for better risk/reward

- Set stop_loss:
  * 10-15% below entry price (allow room for normal volatility over 3-6 months)
  * Place below major support levels (50-day MA, recent swing lows, multi-week support zones)
  * Use 2-3x ATR below entry as volatility-adjusted stop
  * NEVER set stops tighter than 8% for mid-term positions

- Set take_profit:
  * Minimum 20-30% above entry for 3-month targets
  * 30-50% above entry for 6-month targets
  * Place at major resistance levels, previous all-time highs, or measured moves from chart patterns
  * Ensure minimum 2.5:1 reward:risk ratio (preferably 3:1 or better)

- Rationale MUST include:
  * Recent 15+ days price action analysis
  * Any chart patterns (triangles, flags, head-and-shoulders, etc.)
  * Candlestick patterns from recent sessions
  * Key support/resistance levels from price history
  * "Based on [pattern/support level], consider entering at $X (with room for 5-10% pullback if waiting), stop loss at $Y (10-15% below, under support), take profit at $Z (25-40% gain, at resistance)"

For WAIT actions:
- Set wait_for_price: Significant pullback level (8-15% below current) to major support
- Rationale MUST include:
  * "Wait for price to pullback to $X (50-day MA / previous resistance turned support / Fibonacci retracement level)"
  * Recent price action context showing why waiting is prudent
  * What chart pattern or support level you're waiting to test

For REMOVE actions:
- Explain the bearish technical breakdown with specific support violations
- Rationale MUST include:
  * "Price has broken below $X major support level (50-day MA / multi-week low)"
  * Chart pattern breakdown (e.g., "head-and-shoulders neckline break", "triangle breakdown")
  * Bearish candlestick patterns from recent action

ANALYSIS PRIORITIES (IN ORDER):
1. Recent 15+ days price action and chart patterns
2. Major support/resistance levels from price history
3. Candlestick patterns and formations
4. Key moving averages (50-day, 200-day) as dynamic support/resistance
5. Technical indicators (RSI, MACD) for confirmation
6. Volume patterns for conviction

ALWAYS reference actual price levels and patterns from the recent price action in your rationale."""
        else:
            base_prompt += """
GENERAL MODE - Overview Analysis:

Action Mapping (for watchlist management):
- Buy: Strong technical setup, good entry point
- Wait: Mixed signals or not optimal timing
- Remove: Bearish signals, better opportunities elsewhere

Provide detailed rationale explaining your analysis and reasoning."""

        return base_prompt

    def _build_user_prompt(self, ticker: str, indicator_summary: str) -> str:
        """Build user prompt with ticker and indicators.

        Args:
            ticker: Stock ticker symbol
            indicator_summary: Formatted indicator summary

        Returns:
            User prompt string
        """
        base_request = f"""Perform comprehensive mid-term swing trading analysis for {ticker} (3-6 months time horizon).

# Technical Indicators:
{indicator_summary}

Analyze these indicators and recent price action to provide:
1. Overall technical score (0-100)
2. Confidence level in your analysis (0-100)
3. Trading recommendation (strong_buy, buy, hold, sell, strong_sell)
4. Suggested watchlist action (Buy, Wait, Remove)
5. Detailed, fact-based rationale focusing on chart patterns, support/resistance, and price action
6. 2-4 key technical signals driving your analysis
7. 1-3 risk factors or caveats to consider
8. Trend assessment (bullish, bearish, neutral)
9. Entry timing recommendation (immediate, wait_for_pullback, wait_for_breakout, avoid)"""

        if self.prompt_mode == "tactical":
            base_request += """
10. MID-TERM SWING TRADING LEVELS (3-6 months):
    - If action is BUY:
      * entry_price: Current price (if strong momentum) OR 5-10% below at major support (if consolidating)
      * stop_loss: 10-15% below entry, under major support levels (NEVER tighter than 8%)
      * take_profit: 25-40% above entry at major resistance (minimum 2.5:1 R:R, target 3:1+)
    - If action is WAIT:
      * wait_for_price: 8-15% pullback to major support level (50-day MA, previous resistance, Fib level)
    - If action is REMOVE: Set these fields to null

CRITICAL ANALYSIS REQUIREMENTS:

Your rationale MUST analyze IN THIS ORDER:
1. **Recent Price Action (15+ days)**: Describe the price movement, trend, consolidation patterns
   - Is it forming higher highs/lows (uptrend) or lower highs/lows (downtrend)?
   - Any significant breakouts or breakdowns in recent weeks?

2. **Chart Patterns**: Identify any patterns from recent price structure
   - Triangles (ascending, descending, symmetrical)
   - Head and shoulders (or inverse)
   - Double/triple tops or bottoms
   - Flags, pennants, wedges
   - Cup and handle patterns

3. **Candlestick Patterns**: Look at recent candlestick formations
   - Engulfing patterns (bullish/bearish)
   - Hammers, shooting stars
   - Doji, spinning tops
   - Morning/evening stars
   - Three white soldiers / three black crows

4. **Support/Resistance Levels**: Identify key price levels from recent history
   - Where has price repeatedly bounced (support)?
   - Where has price repeatedly stalled (resistance)?
   - Previous highs/lows that now act as levels
   - Round numbers that may act as psychological levels

5. **Moving Averages as Dynamic Levels**:
   - Is price above/below 50-day and 200-day MAs?
   - Are these MAs acting as support or resistance?
   - Golden cross or death cross patterns?

6. **Technical Indicators** (for confirmation only):
   - RSI for overbought/oversold conditions
   - MACD for momentum confirmation
   - Volume for conviction
   - Bollinger Bands for volatility context
   - ATR for stop loss placement guidance

RATIONALE FORMAT (MUST INCLUDE):
- For BUY: "Over the past 15 days, [describe price action]. Price is forming [chart pattern] with support at $[level] and resistance at $[level]. Recent [candlestick pattern] suggests [bullish/bearish momentum]. Consider entering at $[entry_price] with stop loss at $[stop_loss] (10-15% below, under [support level]) and take profit at $[take_profit] (25-40% gain, at [resistance level]). This provides [X]:1 risk-reward ratio for 3-6 month hold."

- For WAIT: "Recent price action shows [describe]. Wait for pullback to $[wait_for_price] which aligns with [50-day MA / previous resistance turned support / Fibonacci retracement]. This would provide better entry with [improved risk/reward]."

- For REMOVE: "Price has broken below $[level] support ([specify: 50-day MA / multi-week low / pattern neckline]). Recent [candlestick pattern] confirms bearish momentum. Better opportunities exist elsewhere."

SWING TRADING PRINCIPLES FOR 3-6 MONTH POSITIONS:
- Entry: Buy near support, not at highs (unless strong breakout with volume)
- Stop Loss: Wide enough to survive normal volatility (10-15%), below major support
- Take Profit: Substantial targets (25-40%+), at major resistance or measured moves
- Risk/Reward: Minimum 2.5:1, preferably 3:1 or better
- Patience: Wait for optimal setups at support levels rather than chasing

Use actual price levels, pattern names, and specific observations from the recent price data in your analysis."""

        return base_request
